name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4  
        - name: Welcome Meassage
          run: echo "Hi It's my First Github Actions Job"

        - name: List Files
          run: ls

        - name: Read file
          run: cat README.md

